# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a81884edc9274608743e4fbf64a62344983563280cf5e6d14e25170518c1c73c361fa51878b6cf643f7251e9939e2424dc9f2f16c71ccccd79043b7082f0fe7c

test:
  secret_key_base: fb53c7afc2dd34ead637eaeb142d78e442f477f5d49cc0ecf7794ee3f16dede576a4370a2ad0751448bf938b441cabb62036ca363ceac357550b866f37fc3cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
